const phoneCodes = [
  { "pais": "Afganistán", "codigo": "+93", "longitud": 9 },
  { "pais": "Albania", "codigo": "+355", "longitud": 9 },
  { "pais": "Alemania", "codigo": "+49", "longitud": 11 },
  { "pais": "Andorra", "codigo": "+376", "longitud": 6 },
  { "pais": "Angola", "codigo": "+244", "longitud": 9 },
  { "pais": "Antigua y Barbuda", "codigo": "+1-268", "longitud": 10 },
  { "pais": "Arabia Saudita", "codigo": "+966", "longitud": 9 },
  { "pais": "Argelia", "codigo": "+213", "longitud": 9 },
  { "pais": "Argentina", "codigo": "+54", "longitud": 10 },
  { "pais": "Armenia", "codigo": "+374", "longitud": 8 },
  { "pais": "Australia", "codigo": "+61", "longitud": 9 },
  { "pais": "Austria", "codigo": "+43", "longitud": 10 },
  { "pais": "Azerbaiyán", "codigo": "+994", "longitud": 9 },
  { "pais": "Bahamas", "codigo": "+1-242", "longitud": 10 },
  { "pais": "Bangladés", "codigo": "+880", "longitud": 10 },
  { "pais": "Baréin", "codigo": "+973", "longitud": 8 },
  { "pais": "Barbados", "codigo": "+1-246", "longitud": 10 },
  { "pais": "Bélgica", "codigo": "+32", "longitud": 8 },
  { "pais": "Belice", "codigo": "+501", "longitud": 7 },
  { "pais": "Benín", "codigo": "+229", "longitud": 8 },
  { "pais": "Bielorrusia", "codigo": "+375", "longitud": 9 },
  { "pais": "Birmania", "codigo": "+95", "longitud": 7 },
  { "pais": "Bolivia", "codigo": "+591", "longitud": 8 },
  { "pais": "Bosnia y Herzegovina", "codigo": "+387", "longitud": 8 },
  { "pais": "Botsuana", "codigo": "+267", "longitud": 8 },
  { "pais": "Brasil", "codigo": "+55", "longitud": 10 },
  { "pais": "Brunéi", "codigo": "+673", "longitud": 7 },
  { "pais": "Bulgaria", "codigo": "+359", "longitud": 9 },
  { "pais": "Burkina Faso", "codigo": "+226", "longitud": 8 },
  { "pais": "Burundi", "codigo": "+257", "longitud": 8 },
  { "pais": "Cabo Verde", "codigo": "+238", "longitud": 7 },
  { "pais": "Camboya", "codigo": "+855", "longitud": 8 },
  { "pais": "Camerún", "codigo": "+237", "longitud": 8 },
  { "pais": "Canadá", "codigo": "+1", "longitud": 10 },
  { "pais": "Catar", "codigo": "+974", "longitud": 8 },
  { "pais": "Chile", "codigo": "+56", "longitud": 9 },
  { "pais": "China", "codigo": "+86", "longitud": 11 },
  { "pais": "Chipre", "codigo": "+357", "longitud": 8 },
  { "pais": "Colombia", "codigo": "+57", "longitud": 10 },
  { "pais": "Comoras", "codigo": "+269", "longitud": 7 },
  { "pais": "Corea del Norte", "codigo": "+850", "longitud": 8 },
  { "pais": "Corea del Sur", "codigo": "+82", "longitud": 9 },
  { "pais": "Costa de Marfil", "codigo": "+225", "longitud": 8 },
  { "pais": "Costa Rica", "codigo": "+506", "longitud": 8 },
  { "pais": "Croacia", "codigo": "+385", "longitud": 9 },
  { "pais": "Cuba", "codigo": "+53", "longitud": 8 },
  { "pais": "Dinamarca", "codigo": "+45", "longitud": 8 },
  { "pais": "Ecuador", "codigo": "+593", "longitud": 9 },
  { "pais": "Egipto", "codigo": "+20", "longitud": 9 },
  { "pais": "El Salvador", "codigo": "+503", "longitud": 8 },
  { "pais": "Emiratos Árabes Unidos", "codigo": "+971", "longitud": 9 },
  { "pais": "Eslovaquia", "codigo": "+421", "longitud": 9 },
  { "pais": "Eslovenia", "codigo": "+386", "longitud": 8 },
  { "pais": "España", "codigo": "+34", "longitud": 9 },
  { "pais": "Estados Unidos", "codigo": "+1", "longitud": 10 },
  { "pais": "Estonia", "codigo": "+372", "longitud": 8 },
  { "pais": "Etiopía", "codigo": "+251", "longitud": 9 },
  { "pais": "Filipinas", "codigo": "+63", "longitud": 10 },
  { "pais": "Finlandia", "codigo": "+358", "longitud": 9 },
  { "pais": "Francia", "codigo": "+33", "longitud": 9 },
  { "pais": "Gabón", "codigo": "+241", "longitud": 7 },
  { "pais": "Gambia", "codigo": "+220", "longitud": 7 },
  { "pais": "Georgia", "codigo": "+995", "longitud": 9 },
  { "pais": "Ghana", "codigo": "+233", "longitud": 9 },
  { "pais": "Grecia", "codigo": "+30", "longitud": 10 },
  { "pais": "Guatemala", "codigo": "+502", "longitud": 8 },
  { "pais": "Guinea", "codigo": "+224", "longitud": 8 },
  { "pais": "Haití", "codigo": "+509", "longitud": 8 },
  { "pais": "Honduras", "codigo": "+504", "longitud": 8 },
  { "pais": "Hungría", "codigo": "+36", "longitud": 8 },
  { "pais": "India", "codigo": "+91", "longitud": 10 },
  { "pais": "Indonesia", "codigo": "+62", "longitud": 10 },
  { "pais": "Irak", "codigo": "+964", "longitud": 10 },
  { "pais": "Irán", "codigo": "+98", "longitud": 10 },
  { "pais": "Irlanda", "codigo": "+353", "longitud": 9 },
  { "pais": "Islandia", "codigo": "+354", "longitud": 7 },
  { "pais": "Israel", "codigo": "+972", "longitud": 9 },
  { "pais": "Italia", "codigo": "+39", "longitud": 10 },
  { "pais": "Jamaica", "codigo": "+1-876", "longitud": 10 },
  { "pais": "Japón", "codigo": "+81", "longitud": 10 },
  { "pais": "Jordania", "codigo": "+962", "longitud": 9 },
  { "pais": "Kazajistán", "codigo": "+7", "longitud": 10 },
  { "pais": "Kenia", "codigo": "+254", "longitud": 9 },
  { "pais": "Kirguistán", "codigo": "+996", "longitud": 9 },
  { "pais": "Kuwait", "codigo": "+965", "longitud": 8 },
  { "pais": "Letonia", "codigo": "+371", "longitud": 8 },
  { "pais": "Líbano", "codigo": "+961", "longitud": 8 },
  { "pais": "Libia", "codigo": "+218", "longitud": 8 },
  { "pais": "Lituania", "codigo": "+370", "longitud": 8 },
  { "pais": "Luxemburgo", "codigo": "+352", "longitud": 9 },
  { "pais": "Macedonia del Norte", "codigo": "+389", "longitud": 8 },
  { "pais": "Madagascar", "codigo": "+261", "longitud": 9 },
  { "pais": "Malasia", "codigo": "+60", "longitud": 9 },
  { "pais": "Malawi", "codigo": "+265", "longitud": 9 },
  { "pais": "Maldivas", "codigo": "+960", "longitud": 7 },
  { "pais": "Malí", "codigo": "+223", "longitud": 8 },
  { "pais": "Malta", "codigo": "+356", "longitud": 8 },
  { "pais": "Marruecos", "codigo": "+212", "longitud": 9 },
  { "pais": "México", "codigo": "+52", "longitud": 10 },
  { "pais": "Moldavia", "codigo": "+373", "longitud": 8 },
  { "pais": "Mónaco", "codigo": "+377", "longitud": 8 },
  { "pais": "Mongolia", "codigo": "+976", "longitud": 8 },
  { "pais": "Montenegro", "codigo": "+382", "longitud": 8 },
  { "pais": "Mozambique", "codigo": "+258", "longitud": 9 },
  { "pais": "Namibia", "codigo": "+264", "longitud": 9 },
  { "pais": "Nepal", "codigo": "+977", "longitud": 10 },
  { "pais": "Nicaragua", "codigo": "+505", "longitud": 8 },
  { "pais": "Nigeria", "codigo": "+234", "longitud": 10 },
  { "pais": "Noruega", "codigo": "+47", "longitud": 8 },
  { "pais": "Nueva Zelanda", "codigo": "+64", "longitud": 9 },
  { "pais": "Omán", "codigo": "+968", "longitud": 8 },
  { "pais": "Países Bajos", "codigo": "+31", "longitud": 9 },
  { "pais": "Pakistán", "codigo": "+92", "longitud": 10 },
  { "pais": "Panamá", "codigo": "+507", "longitud": 8 },
  { "pais": "Paraguay", "codigo": "+595", "longitud": 9 },
  { "pais": "Perú", "codigo": "+51", "longitud": 9 },
  { "pais": "Polonia", "codigo": "+48", "longitud": 9 },
  { "pais": "Portugal", "codigo": "+351", "longitud": 9 },
  { "pais": "Reino Unido", "codigo": "+44", "longitud": 10 },
  { "pais": "República Centroafricana", "codigo": "+236", "longitud": 8 },
  { "pais": "República Checa", "codigo": "+420", "longitud": 9 },
  { "pais": "República Dominicana", "codigo": "+1-809", "longitud": 10 },
  { "pais": "Rumanía", "codigo": "+40", "longitud": 10 },
  { "pais": "Rusia", "codigo": "+7", "longitud": 10 },
  { "pais": "Senegal", "codigo": "+221", "longitud": 9 },
  { "pais": "Serbia", "codigo": "+381", "longitud": 8 },
  { "pais": "Singapur", "codigo": "+65", "longitud": 8 },
  { "pais": "Siria", "codigo": "+963", "longitud": 9 },
  { "pais": "Sudáfrica", "codigo": "+27", "longitud": 9 },
  { "pais": "Sudán", "codigo": "+249", "longitud": 9 },
  { "pais": "Suecia", "codigo": "+46", "longitud": 9 },
  { "pais": "Suiza", "codigo": "+41", "longitud": 9 },
  { "pais": "Tailandia", "codigo": "+66", "longitud": 9 },
  { "pais": "Tanzania", "codigo": "+255", "longitud": 9 },
  { "pais": "Túnez", "codigo": "+216", "longitud": 8 },
  { "pais": "Turquía", "codigo": "+90", "longitud": 10 },
  { "pais": "Ucrania", "codigo": "+380", "longitud": 9 },
  { "pais": "Uganda", "codigo": "+256", "longitud": 9 },
  { "pais": "Uruguay", "codigo": "+598", "longitud": 9 },
  { "pais": "Uzbekistán", "codigo": "+998", "longitud": 9 },
  { "pais": "Venezuela", "codigo": "+58", "longitud": 10 },
  { "pais": "Vietnam", "codigo": "+84", "longitud": 9 },
  { "pais": "Yemen", "codigo": "+967", "longitud": 9 },
  { "pais": "Zambia", "codigo": "+260", "longitud": 9 },
  { "pais": "Zimbabue", "codigo": "+263", "longitud": 9 }
]
export default phoneCodes;
