version: '3.8'

services:
  web:
    image: node:22.14
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run build && npm start"

  nginx:
    image: nginx:latest
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /nginx/nginx.conf
        read_only: true
    ports:
      - '80:80'
