version: '3.8'

services:
  web:
    image: node:22.14
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
    command: >
      sh -c "
      if [ \"$NODE_ENV\" = 'production' ]; then
        npm install && npm run build && npm start;
      else
        npm install && npm run dev;
      fi
      "
    networks:
      - shared_net

  nginx:
    image: nginx:latest
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /nginx/nginx.conf
        read_only: true
    ports:
      - '80:80'
    networks:
      - shared_net
networks:
  shared_net:
    driver: bridge