import { Smile, Syringe, Stethoscope, Activity, Heart, Users } from "lucide-react"

// Specialty information with improved images and professional icons
export const especialidadesInfo = {
  "todas": {
    title: "Todas las Especialidades",
    description: "Directorio completo de especialistas odontológicos.",
    color: "#073B4C",
    image: "/assets/especialistas/Todas.avif",
    icon: <Users className="w-6 h-6 text-white" />,
  },
  "ARMONIZCAIÓNFACIAL": {
    title: "Armonización Facial",
    description: "Procedimientos estéticos y funcionales para mejorar la armonía facial y la sonrisa.",
    color: "#FF6B6B",
    image: "/assets/especialistas/ArmonizacionFacial.avif",
    icon: <Smile className="w-6 h-6 text-white" />,
  },
  "CIRUGÍABUCAL": {
    title: "Cirugía Bucal",
    description: "Diagnóstico y tratamiento quirúrgico de patologías en la cavidad oral.",
    color: "#4ECDC4",
    image: "/assets/especialistas/CirugiaBucal.avif",
    icon: <Syringe className="w-6 h-6 text-white" />,
  },
  "CIRUGÍABUCOMAXILOFACIAL": {
    title: "Cirugía Bucomaxilofacial",
    description: "Tratamiento de traumatismos y defectos de los maxilares y región facial.",
    color: "#ffba1a",
    image: "/assets/especialistas/CirugíaBucomaxilofacial.avif",
    icon: <Stethoscope className="w-6 h-6 text-white" />,
  },
  "ENDODONCIA": {
    title: "Endodoncia",
    description: "Tratamiento de la pulpa dental y tejidos perirradiculares.",
    color: "#06D6A0",
    image: "/assets/especialistas/Endodoncia.avif",
    icon: <Activity className="w-6 h-6 text-white" />,
  },
  "ORTODONCIA": {
    title: "Ortodoncia",
    description: "Corrección de anomalías de posición y desarrollo de maxilares y dientes.",
    color: "#118AB2",
    image: "/assets/especialistas/Ortodoncia.avif",
    icon: <Heart className="w-6 h-6 text-white" />,
  },
}

export const especialidadesData = [
  // Armonización Facial
  {
    id: 1,
    nombres: "YULIANA LISETT",
    apellidos: "COLS GUTIERREZ",
    libro: "3237",
    folio: "A-125",
    numEspecialidad: "7271592052",
    cedula: "V-15.789.632",
    cov: "COV-12547",
    especialidad: "ARMONIZCAIÓNFACIAL",
  },
  {
    id: 2,
    nombres: "CARLOS EDUARDO",
    apellidos: "AGUILAR MENDEZ",
    libro: "4125",
    folio: "B-087",
    numEspecialidad: "8362719405",
    cedula: "V-18.456.321",
    cov: "COV-14785",
    especialidad: "ARMONIZCAIÓNFACIAL",
  },
  {
    id: 3,
    nombres: "MARIA FERNANDA",
    apellidos: "BOLIVAR RAMIREZ",
    libro: "2981",
    folio: "C-254",
    numEspecialidad: "6152839405",
    cedula: "V-20.147.852",
    cov: "COV-15874",
    especialidad: "ARMONIZCAIÓNFACIAL",
  },
  {
    id: 4,
    nombres: "JOSE ANTONIO",
    apellidos: "DIAZ TORRES",
    libro: "3562",
    folio: "A-365",
    numEspecialidad: "9273615482",
    cedula: "V-14.258.963",
    cov: "COV-10254",
    especialidad: "ARMONIZCAIÓNFACIAL",
  },

  // Cirugía Bucal
  {
    id: 5,
    nombres: "ANA CAROLINA",
    apellidos: "ESTRADA FUENTES",
    libro: "4023",
    folio: "B-147",
    numEspecialidad: "5182736492",
    cedula: "V-19.874.563",
    cov: "COV-18745",
    especialidad: "CIRUGÍABUCAL",
  },
  {
    id: 6,
    nombres: "ROBERTO CARLOS",
    apellidos: "FERNANDEZ LOPEZ",
    libro: "3198",
    folio: "C-078",
    numEspecialidad: "8273645192",
    cedula: "V-17.456.321",
    cov: "COV-13698",
    especialidad: "CIRUGÍABUCAL",
  },
  {
    id: 7,
    nombres: "PATRICIA ELENA",
    apellidos: "GONZALEZ MARTINEZ",
    libro: "3741",
    folio: "A-214",
    numEspecialidad: "6273819405",
    cedula: "V-16.325.874",
    cov: "COV-14523",
    especialidad: "CIRUGÍABUCAL",
  },
  {
    id: 8,
    nombres: "MIGUEL ANGEL",
    apellidos: "HERNANDEZ PEREZ",
    libro: "2876",
    folio: "B-325",
    numEspecialidad: "9182736450",
    cedula: "V-21.456.987",
    cov: "COV-17896",
    especialidad: "CIRUGÍABUCAL",
  },

  // Cirugía Bucomaxilofacial
  {
    id: 9,
    nombres: "LAURA BEATRIZ",
    apellidos: "JIMENEZ RODRIGUEZ",
    libro: "4310",
    folio: "C-196",
    numEspecialidad: "7263548192",
    cedula: "V-15.963.258",
    cov: "COV-12587",
    especialidad: "CIRUGÍABUCOMAXILOFACIAL",
  },
  {
    id: 10,
    nombres: "DANIEL ALEJANDRO",
    apellidos: "LOPEZ SANCHEZ",
    libro: "3654",
    folio: "A-287",
    numEspecialidad: "8172635492",
    cedula: "V-18.741.258",
    cov: "COV-15478",
    especialidad: "CIRUGÍABUCOMAXILOFACIAL",
  },
  {
    id: 11,
    nombres: "GABRIELA SOFIA",
    apellidos: "MARTINEZ VARGAS",
    libro: "3089",
    folio: "B-174",
    numEspecialidad: "6273819405",
    cedula: "V-19.632.587",
    cov: "COV-16325",
    especialidad: "CIRUGÍABUCOMAXILOFACIAL",
  },
  {
    id: 12,
    nombres: "FRANCISCO JAVIER",
    apellidos: "NAVARRO TORRES",
    libro: "4217",
    folio: "C-258",
    numEspecialidad: "9182736450",
    cedula: "V-16.987.452",
    cov: "COV-13654",
    especialidad: "CIRUGÍABUCOMAXILOFACIAL",
  },

  // Endodoncia
  {
    id: 13,
    nombres: "CAROLINA ANDREA",
    apellidos: "OCHOA VELASQUEZ",
    libro: "3521",
    folio: "A-369",
    numEspecialidad: "7162534980",
    cedula: "V-20.365.874",
    cov: "COV-17458",
    especialidad: "ENDODONCIA",
  },
  {
    id: 14,
    nombres: "RICARDO JOSE",
    apellidos: "PEREZ GONZALEZ",
    libro: "2947",
    folio: "B-258",
    numEspecialidad: "8273645019",
    cedula: "V-15.478.963",
    cov: "COV-12365",
    especialidad: "ENDODONCIA",
  },
  {
    id: 15,
    nombres: "VALENTINA ISABEL",
    apellidos: "QUINTERO HERNANDEZ",
    libro: "4102",
    folio: "C-147",
    numEspecialidad: "6152738490",
    cedula: "V-18.963.254",
    cov: "COV-15698",
    especialidad: "ENDODONCIA",
  },
  {
    id: 16,
    nombres: "SEBASTIAN ANDRES",
    apellidos: "RAMIREZ JIMENEZ",
    libro: "3785",
    folio: "A-258",
    numEspecialidad: "9273615480",
    cedula: "V-17.852.369",
    cov: "COV-14789",
    especialidad: "ENDODONCIA",
  },

  // Ortodoncia
  {
    id: 17,
    nombres: "ALEJANDRA MARIA",
    apellidos: "SANCHEZ LOPEZ",
    libro: "3147",
    folio: "B-369",
    numEspecialidad: "7162538490",
    cedula: "V-19.258.741",
    cov: "COV-16987",
    especialidad: "ORTODONCIA",
  },
  {
    id: 18,
    nombres: "JAVIER EDUARDO",
    apellidos: "TORRES MARTINEZ",
    libro: "4258",
    folio: "C-258",
    numEspecialidad: "8273615490",
    cedula: "V-16.325.478",
    cov: "COV-13258",
    especialidad: "ORTODONCIA",
  },
  {
    id: 19,
    nombres: "MARIANA ISABEL",
    apellidos: "URIBE NAVARRO",
    libro: "3698",
    folio: "A-147",
    numEspecialidad: "6152738490",
    cedula: "V-21.478.963",
    cov: "COV-18523",
    especialidad: "ORTODONCIA",
  },
  {
    id: 20,
    nombres: "ANDRES FELIPE",
    apellidos: "VARGAS PEREZ",
    libro: "2874",
    folio: "B-258",
    numEspecialidad: "9273615480",
    cedula: "V-15.369.852",
    cov: "COV-12478",
    especialidad: "ORTODONCIA",
  },
]