const EstadoData = {
    "amazonas": [
        "Alto Orinoco",
        "Atabapo",
        "Atures",
        "Autana",
        "Manapiare",
        "Maroa",
        "Río Negro"
    ],
    "anzoátegui": [
        "Anaco",
        "Aragua",
        "Bolívar",
        "Bruzual",
        "Cajigal",
        "Carvajal",
        "Diego Bautista Urbaneja",
        "Freites",
        "Guanipa",
        "Guanta",
        "Independencia",
        "Juan Antonio Sotillo",
        "Libertad",
        "McGregor",
        "Miranda",
        "Monagas",
        "Peñalver",
        "Píritu",
        "San Juan de Capistrano",
        "Santa Ana",
        "Simón Rodríguez"
    ],
    "apure": [
        "Achaguas",
        "Biruaca",
        "Muñoz",
        "Páez",
        "Pedro Camejo",
        "Rómulo Gallegos",
        "San Fernando"
    ],
    "aragua": [
        "Bolívar",
        "Camatagua",
        "Francisco Linares Alcántara",
        "Girardot",
        "José Ángel Lamas",
        "José Félix Ribas",
        "José Rafael Revenga",
        "Libertador",
        "Mario Briceño Iragorry",
        "Ocumare de la Costa de Oro",
        "San Casimiro",
        "San Sebastián",
        "Santiago Mariño",
        "Santos Michelena",
        "Sucre",
        "Tovar",
        "Urdaneta",
        "Zamora"
    ],
    "barinas": [
        "Alberto Arvelo Torrealba",
        "Andrés Eloy Blanco",
        "Antonio José de Sucre",
        "Arismendi",
        "Barinas",
        "Bolívar",
        "Cruz Paredes",
        "Ezequiel Zamora",
        "Obispos",
        "Pedraza",
        "Rojas",
        "Sosa"
    ],
    "bolívar": [
        "Angostura del Orinoco",
        "Caroní",
        "Cedeño",
        "El Callao",
        "Gran Sabana",
        "Heres",
        "Piar",
        "Raúl Leoni",
        "Roscio",
        "Sifontes",
        "Sucre"
    ],
    "carabobo": [
        "Bejuma",
        "Carlos Arvelo",
        "Diego Ibarra",
        "Guacara",
        "Juan José Mora",
        "Libertador",
        "Los Guayos",
        "Miranda",
        "Montalbán",
        "Naguanagua",
        "Puerto Cabello",
        "San Diego",
        "San Joaquín",
        "Valencia"
    ],
    "cojedes": [
        "Anzoátegui",
        "Ezequiel Zamora",
        "Girardot",
        "Lima Blanco",
        "Pao de San Juan Bautista",
        "Ricaurte",
        "Rómulo Gallegos",
        "San Carlos",
        "Tinaco"
    ],
    "delta amacuro": [
        "Antonio Díaz",
        "Casacoima",
        "Pedernales",
        "Tucupita"
    ],
    "distrito capital": [
        "23 de Enero",
        "Altagracia",
        "Antímano",
        "Candelaria",
        "Caricuao",
        "Catedral",
        "Coche",
        "El Junquito",
        "El Paraíso",
        "El Recreo",
        "El Valle",
        "La Pastora",
        "La Vega",
        "Macarao",
        "San Agustín",
        "San Bernardino",
        "San José",
        "San Juan",
        "San Pedro",
        "Santa Rosalía",
        "Santa Teresa",
        "Sucre"
    ],
    "falcón": [
        "Acosta",
        "Bolívar",
        "Buchivacoa",
        "Cacique Manaure",
        "Carirubana",
        "Colina",
        "Dabajuro",
        "Democracia",
        "Falcón",
        "Federación",
        "Jacura",
        "Los Taques",
        "Mauroa",
        "Miranda",
        "Monseñor Iturriza",
        "Palmasola",
        "Petit",
        "Píritu",
        "San Francisco",
        "Silva",
        "Sucre",
        "Tocópero",
        "Unión",
        "Urumaco",
        "Zamora"
    ],
    "guárico": [
        "Camaguán",
        "Chaguaramas",
        "El Socorro",
        "Francisco de Miranda",
        "José Félix Ribas",
        "José Tadeo Monagas",
        "Juan Germán Roscio",
        "Julián Mellado",
        "Las Mercedes",
        "Leonardo Infante",
        "Ortiz",
        "San Gerónimo de Guayabal",
        "San José de Guaribe",
        "Santa María de Ipire",
        "Zaraza"
    ],
    "lara": [
        "Andrés Eloy Blanco",
        "Crespo",
        "Iribarren",
        "Jiménez",
        "Morán",
        "Palavecino",
        "Simón Planas",
        "Torres",
        "Urdaneta"
    ],
    "la guaira": [
        "Caraballeda",
        "Carayaca",
        "Carlos Soublette",
        "Catia La Mar",
        "El Junko",
        "La Guaira",
        "Macuto",
        "Maiquetía",
        "Naiguatá",
        "Urimare"
    ],
    "mérida": [
        "Alberto Adriani",
        "Andrés Bello",
        "Antonio Pinto Salinas",
        "Aricagua",
        "Arzobispo Chacón",
        "Campo Elías",
        "Caracciolo Parra Olmedo",
        "Cardenal Quintero",
        "Guaraque",
        "Julio César Salas",
        "Justo Briceño",
        "Libertador",
        "Miranda",
        "Obispo Ramos de Lora",
        "Padre Noguera",
        "Pueblo Llano",
        "Rangel",
        "Rivas Dávila",
        "Santos Marquina",
        "Sucre",
        "Tovar",
        "Tulio Febres Cordero",
        "Zea"
    ],
    "miranda": [
        "Acevedo",
        "Andrés Bello",
        "Baruta",
        "Brión",
        "Buroz",
        "Carrizal",
        "Chacao",
        "Cristóbal Rojas",
        "El Hatillo",
        "Guaicaipuro",
        "Independencia",
        "Lander",
        "Los Salias",
        "Páez",
        "Paz Castillo",
        "Pedro Gual",
        "Plaza",
        "Simón Bolívar",
        "Sucre",
        "Urdaneta",
        "Zamora"
    ],
    "monagas": [
        "Acosta",
        "Aguasay",
        "Bolívar",
        "Caripe",
        "Cedeño",
        "Ezequiel Zamora",
        "Libertador",
        "Maturín",
        "Piar",
        "Punceres",
        "Santa Bárbara",
        "Sotillo",
        "Uracoa"
    ],
    "nueva esparta": [
        "Antolín del Campo",
        "Arismendi",
        "Díaz",
        "García",
        "Gómez",
        "Maneiro",
        "Marcano",
        "Mariño",
        "Península de Macanao",
        "Tubores",
        "Villalba"
    ],
    "portuguesa": [
        "Agua Blanca",
        "Araure",
        "Esteller",
        "Guanare",
        "Guanarito",
        "José Vicente de Unda",
        "Ospino",
        "Páez",
        "Papelón",
        "San Genaro de Boconoito",
        "San Rafael de Onoto",
        "Santa Rosalía",
        "Sucre",
        "Turén"
    ],
    "sucre": [
        "Andrés Eloy Blanco",
        "Andrés Mata",
        "Arismendi",
        "Benítez",
        "Bermúdez",
        "Bolívar",
        "Cajigal",
        "Cruz Salmerón Acosta",
        "Libertador",
        "Mariño",
        "Mejía",
        "Montes",
        "Ribero",
        "Sucre",
        "Valdez"
    ],
    "táchira": [
        "Andrés Bello",
        "Antonio Rómulo Costa",
        "Ayacucho",
        "Bolívar",
        "Cárdenas",
        "Córdoba",
        "Fernández Feo",
        "Francisco de Miranda",
        "García de Hevia",
        "Guásimos",
        "Independencia",
        "Jáuregui",
        "José María Vargas",
        "Junín",
        "Libertad",
        "Libertador",
        "Lobatera",
        "Michelena",
        "Panamericano",
        "Pedro María Ureña",
        "Rafael Urdaneta",
        "Samuel Darío Maldonado",
        "San Cristóbal",
        "San Judas Tadeo",
        "Seboruco",
        "Simón Rodríguez",
        "Sucre",
        "Torbes",
        "Uribante"
    ],
    "trujillo": [
        "Andrés Bello",
        "Boconó",
        "Bolívar",
        "Candelaria",
        "Carache",
        "Escuque",
        "José Felipe Márquez Cañizales",
        "Juan Vicente Campo Elías",
        "La Ceiba",
        "Miranda",
        "Monte Carmelo",
        "Motatán",
        "Pampán",
        "Pampanito",
        "Rafael Rangel",
        "San Rafael de Carvajal",
        "Sucre",
        "Trujillo",
        "Urdaneta",
        "Valera"
    ],
    "yaracuy": [
        "Arístides Bastidas",
        "Bolívar",
        "Bruzual",
        "Cocorote",
        "Independencia",
        "José Antonio Páez",
        "La Trinidad",
        "Manuel Monge",
        "Nirgua",
        "Peña",
        "San Felipe",
        "Sucre",
        "Urachiche",
        "Veroes"
    ],
    "zulia": [
        "Almirante Padilla",
        "Baralt",
        "Cabimas",
        "Catatumbo",
        "Colón",
        "Francisco Javier Pulgar",
        "Jesús Enrique Lossada",
        "Jesús María Semprún",
        "La Cañada de Urdaneta",
        "Lagunillas",
        "Machiques de Perijá",
        "Mara",
        "Maracaibo",
        "Miranda",
        "Rosario de Perijá",
        "San Francisco",
        "Santa Rita",
        "Simón Bolívar",
        "Sucre",
        "Valmore Rodríguez"
    ]
};

export default EstadoData;
